### PR TITLE
 Refactor and Enhance Tic-Tac-Toe Backend

### PR DESCRIPTION
**Pull request by hackerSa3edy**
Description:

This Pull Request implements a significant refactor and enhancement of the Tic-Tac-Toe backend application. The changes include a complete restructuring of the server application, implementation of core game logic, user management, authentication, and database integration. Additionally, it introduces Docker support for easier deployment and development.

Key Changes:

1. Application Structure and Configuration:
   - Refactored the Flask application initialization for improved modularity and maintainability.
   - Implemented environment-specific configurations (development, production).
   - Added support for loading environment variables from .env files.

2. Authentication and User Management:
   - Implemented a robust authentication system with user registration, login, logout, and session management.
   - Created routes for authentication-related actions.
   - Integrated bcrypt for secure password hashing.

3. Game Logic and API:
   - Implemented core game logic for Tic-Tac-Toe.
   - Created API routes for game-related operations (start game, make move, end game).
   - Added user and leaderboard functionality.

4. Database Integration:
   - Set up MongoDB integration with collections for users, games, sessions, and leaderboard.
   - Implemented database initialization and schema validation.

5. Real-time Communication:
   - Integrated Socket.IO for real-time game updates.
   - Implemented event handlers for game moves and messages.
   - Added a test client for Socket.IO functionality.

6. Error Handling and Middleware:
   - Implemented custom error handlers for common HTTP errors.
   - Added middleware for route protection and potential rate limiting.

7. Dockerization:
   - Created Dockerfile for the backend service.
   - Set up docker-compose.yml for orchestrating backend and MongoDB services.

8. Documentation:
   - Significantly updated README.md with comprehensive project information, setup instructions, and deployment guide.
   - Added inline comments and docstrings for better code understanding.

9. Development Tools:
   - Updated requirements.txt with all necessary Python packages.

10. Security Enhancements:
    - Implemented CORS with configurable origins.
    - Used environment variables for sensitive information.

Testing:
- Added a Socket.IO client test script.
- Manual testing performed for authentication, game logic, and real-time communication.

Deployment:
- The application can now be easily deployed using Docker and Docker Compose.
- Added detailed deployment instructions in the README.md.

Next Steps:
- Enhance AI player logic.
- Enhance multi-player logic.
- Enhance the player pairing algorithm.
- Create a game, user, leaderboard model, and their rouets and utils.
- Create middleware functions like Control what routes to access.

### CODE REVIEW

**Comment by Justxd22** [comment]
Appreciate the effort, But unfortunately i can't accept this PR for the following reasons:

- Simply because it's untested code
- env is broken `dotenv_path="../.env"` doesn't actually load .env at `/server/.env`
- Local Database URI is broken `"mongodb://mongodb-username:mongodb-password@localhost:27017"`
- `development.py` and `production.py` are both broken since u need to re- `load_dotenv()` for env to actually populate or it will take default values and ignore our .env
- `app.py` is broken because `socketio.run` doesn't take `async_mode='eventlet'` again untested code
- all socket events from frontend returns `400`
- all api routes are broken returns `404` again untested code
- cors errors everywhere
- looks like auth was moved to `/api/auth` while the frontend is still using `/` That will break the frontend
Screenshot 2024-08-26 033112
Screenshot 2024-08-26 033058


We don't have either the man power or the time to merge and patch fix what was broken, and i don't see new features other than flask sessions and docker file, i can't test the db validation

**Comment by hackerSa3edy** [comment]
1. 
> Appreciate the effort, But unfortunately i can't accept this PR for the following reasons:
> 
> * Simply because it's untested code

Actually, this works fine in containers, I missed testing this with development environments

2.
> * env is broken `dotenv_path="../.env"` doesn't actually load .env at `/server/.env`

Acknowledged and fixed in 05133ae 

3.
> * Local Database URI is broken `"mongodb://mongodb-username:mongodb-password@localhost:27017"`

You should add your MongoDB username, password, and database name. Therefore, create the database, set up a user, and assign the minimum privileges - read and write access exclusively to the created database. The final URI should be `"mongodb://mongodb-username:mongodb-password@localhost:27017/db_name"`

4.
> * `development.py` and `production.py` are both broken since u need to re- `load_dotenv()` for env to actually populate or it will take default values and ignore our .env

Acknowledged and fixed in 05133ae

5.
> * `app.py` is broken because `socketio.run` doesn't take `async_mode='eventlet'` again untested code

Acknowledged and fixed in 05133ae. This part is only executed in development so I missed this.

6.
> * all socket events from frontend returns `400`

Events work well, I will give it a look at the client side.
Server:
image
Socket client:
image


7.
> * all api routes are broken returns `404` again untested code

All API routes work well.
image

8.
> * cors errors everywhere
I am working on making sure to enforce CORS for all the routes.

9.
> * looks like auth was moved to `/api/auth` while the frontend is still using `/` That will break the frontend

All the routes were clear in the docs, the API routes will have `/api/auth/` prefix. This isn't a big problem in the front end, just prefix the auth routes with `/api/auth/`.

**Review by 0x3mr — APPROVED** [review]

**Comment by Justxd22** [comment]
## 3. local database
nah in local we don't have any username/password that's way there was db auth error maybe place a fallback to loacl uri without username/pass for dev env? `MONGO_URI=mongodb://localhost:27017/` is the one working for me 

## 6. sockets 
screenshot attached is from frontend that returns `400` maybe it was cors

## 7. api
yes it's broken because of the frontend using `/` not `/api/auth` and CORS

## 9. 
please fix `login.tsx` and other to follow new routes

**Comment by Justxd22** [comment]
`server/multiplayer_socketIO/events.py` was commented out??

**Comment by Justxd22** [comment]
`/server/config/default.py`
remove these
```py
    elif MONGO_DB_USERNAME is None:
        raise ValueError("No MONGO_DB_USERNAME set for Flask application")
    elif MONGO_DB_PASSWD is None:
        raise ValueError("No MONGO_DB_PASSWD set for Flask application")
```
As in local we don't actually have users by default and the fallback to `None` would be fine

**Comment by Justxd22** [comment]
Sockets still `400` from frontend
image

**Pull request merged**
